name: C++ Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build tests
        working-directory: cpp-unit-test
        run: |
          g++ -std=c++17 catch_amalgamated.cpp test_calculator.cpp calculator.cpp -o tests

      - name: Run unit tests
        working-directory: cpp-unit-test
        run: ./tests -s -v high
