name: Pytest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: python-unit-test
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then
            pip install .
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        working-directory: python-unit-test
        run: pytest -v
